Index: Makefile
===================================================================
--- Makefile	(Revision 22)
+++ Makefile	(Arbeitskopie)
@@ -10,7 +10,7 @@
 
 PKG_NAME:=batman-adv-devel
 
-PKG_BATMAN_REV:=b82b9b254c8a923fb2d65e2ca3eefc2e8b4429e7
+PKG_BATMAN_REV:=ebdc92a614b3de8a32c66c92a46df286afe4bf6a
 PKG_BATCTL_REV:=d9ee7eed3175992be75e2cb949c048bdddeb0769
 
 PKG_BATMAN_BRANCH:=$(subst ",,$(CONFIG_KMOD_BATMAN_ADV_DEVEL_BRANCH_NAME))
