config 'wifi-device' 'wifi0'
	option 'type' 'mac80211'
	option 'phy' 'phy0'
	option 'disabled' '0'
	option 'channel' '${BATMAN_CHANNEL}'
    option 'hwmode' '11g'

config 'wifi-iface'
	option 'device' 'wifi0'
	option 'network' 'wlanmesh'
	option 'mode' 'adhoc'
	option 'ssid' '${ESSID_MESH}'
	option 'bssid' '${BSSID_MESH}'
	option 'encryption' 'none'
	option 'hidden' '1'

config 'wifi-iface'
	option 'device' 'wifi0'
	option 'network' 'mesh'
	option 'mode' 'ap'
	option 'ssid' '${ESSID_AP}'
	option 'encryption' 'none'
